### ISSUE TITLE
Index error and application error when staging new file

### ISSUE THREAD

**Issue by johnjohndoe** [prati0100/git-gui#36] opened 2020-04-28 14:28 UTC
I am running _git-gui version 0.21.GITGUI_ with _git version 2.26.2.windows.1_ on Windows 10.  
When I stage a new file the following error is shown in a popup window:

> Index Error  
> Updating the Git index failed.  A rescan will be automatically started to resynchronize git-gui.  
>  
> warning: CRLF will be replaced by LF in path/to/file.  
> The file will have its original line endings in your working directory

I can choose to "Unlock Index" or "Continue".
I choose "Continue". The former window closes and a new error window pops up:

> Application Error:  
> Error: wrong # args: should be "ui_ready"

```
wrong # args: should be "ui_ready"
wrong # args: should be "ui_ready"
    while executing
"ui_ready ui_ready"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 $after"
    (procedure "select_first_diff" line 8)
    invoked from within
"select_first_diff $after "
    (procedure "rescan_done" line 15)
    invoked from within
"rescan_done $fd buf_rlo $after"
    (procedure "read_ls_others" line 14)
    invoked from within
"read_ls_others file3d689f0 {reshow_diff; ui_ready ui_ready}"
```

When I choose "OK" then the windows closes and the file is staged.

**Comment by prati0100** [comment] 2020-04-29 08:48
A similar problem was reported some time ago. A contributor proposed a fix that you can find [here](https://github.com/prati0100/git-gui/commit/19195fbd73994d05abaa0a2976143da96b320f47). Does this fix the issue for you.

This will fix the "wrong # args" problem. The index error is a harder problem, and I'm not sure how to reproduce it.

**Comment by johnjohndoe** [comment] 2020-04-29 10:36
> Does this fix the issue for you?

The change reads suitable for me. Is the patched version available somewhere or would I need to build _git-gui_ myself?

> The index error is a harder problem, and I'm not sure how to reproduce it.

Is there anything I can add so you got more information?

**Comment by prati0100** [comment] 2020-04-29 11:07
> The change reads suitable for me. Is the patched version available somewhere or would I need to build _git-gui_ myself?

I don't run any kind of CI/CD system on the repo, so I think you would need to build it yourself. I don't use Windows, so I'm not sure if the development environment is easily available there.

Since the change is quite small, and all of git-gui is just plain text scripts, maybe you can just manually edit them to test. Check [here](https://github.com/git-for-windows/git/issues/2469#issuecomment-621028545) to find out how. Of course, take backups just in case.

> Is there anything I can add so you got more information?

If you can provide a simple contained example to reproduce the problem, it would be a pretty good start.

**Comment by prati0100** [comment] 2020-05-05 12:35
Fixed in https://github.com/prati0100/git-gui/commit/88db24d724619d6c2e602c3b56016f59326d31e3

Please feel free to re-open the issue if the problem persists.

**Closed by prati0100** 2020-05-05 12:35 UTC

**Comment by johnjohndoe** [comment] 2020-05-05 15:51
@prati0100 Thanks for the reminder. I can confirm that error messages disappear with the manually applied patch. I just did quick test right now. I will keep it and see how it behaves in the upcoming days. Thank you. Please mention here once the patch is releases in a new version of Git.

**Comment by prati0100** [comment] 2020-05-05 19:00
Thanks for testing.

> Please mention here once the patch is releases in a new version of Git.

I'll probably forget to remind you. It should land into Git v2.27.0 which is due June 1st. If you want it to land in Git for Windows sooner, you might try asking the GfW maintainer [here](https://github.com/git-for-windows/git/issues/2469#issuecomment-624023333).
